-- 094: 扩充职位训练题库（多职位 × 技能维度 × 难度分级）
-- 幂等：INSERT ... ON CONFLICT (id) DO UPDATE

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-PMC-Q07', 'pmc', 'PT-PMC-Q07', '备料齐套', 2, 'single',
 'MRP 提示某物料将在计划开工日之后才到货，PMC 第一时间应该？',
 '[{"value":"a","label":"直接修改工单开工时间，不通知任何部门"},{"value":"b","label":"核对到货ETA与物料上线红线的差值，评估是否调整排产或升级采购"},{"value":"c","label":"把该料从BOM里删掉保证齐套"},{"value":"d","label":"等工单报工时再处理"}]'::jsonb,
 '["b"]'::jsonb,
 '缺料到货时间必须与上线红线比较，红线=开工-安全缓冲；缺口形成决策项并升级。',
 '["MRP","ETA","上线红线"]'::jsonb, 2),
('PT-PMC-Q08', 'pmc', 'PT-PMC-Q08', '产能约束', 2, 'single',
 '瓶颈工位已满载，新订单加急 3 天，PMC 应优先评估？',
 '[{"value":"a","label":"直接回绝订单"},{"value":"b","label":"直接全盘重排所有工单"},{"value":"c","label":"评估瓶颈工位可用窗口、能力外协/加班可行性，给出有条件承诺"},{"value":"d","label":"仅看成品库存是否足够"}]'::jsonb,
 '["c"]'::jsonb,
 'CTP 思路：承诺前必须验证瓶颈产能窗口与替代方案，不是简单拒绝或盲目重排。',
 '["瓶颈","CTP","外协","可用窗口"]'::jsonb, 2),
('PT-PMC-Q09', 'pmc', 'PT-PMC-Q09', '交期倒排', 3, 'single',
 '客户 RDD 已定，进行交期倒排时，正确顺序是？',
 '[{"value":"a","label":"成品出运=客户RDD，逐级倒推包装、装配、加工、备料的完成时点"},{"value":"b","label":"从今天起逐日顺推，看哪天能做好"},{"value":"c","label":"按生产主管感觉排"},{"value":"d","label":"先排装配再排采购，出运时间最后定"}]'::jsonb,
 '["a"]'::jsonb,
 '倒排以客户承诺为锚，反向推导各环节完成节点，若某级不满足则升级或调整承诺。',
 '["RDD","倒排","FG Ready","ETD"]'::jsonb, 3),
('PT-PMC-Q10', 'pmc', 'PT-PMC-Q10', '插单仲裁', 3, 'multiple',
 '新增紧急订单需要插单，PMC 应携带哪些证据进入仲裁？(多选)',
 '[{"value":"a","label":"对既有在制工单交期的影响评估"},{"value":"b","label":"插单订单的物料齐套与到料计划"},{"value":"c","label":"瓶颈工位可用产能与加班/外协成本"},{"value":"d","label":"业务方对该订单的客户价值陈述"}]'::jsonb,
 '["a","b","c","d"]'::jsonb,
 '插单决策必须同时给出对已承诺订单的影响、物料与产能证据，以及业务层面的价值判断。',
 '["插单","优先级仲裁","影响评估"]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-OP-Q01', 'operator', 'PT-OP-Q01', '首件确认', 1, 'single',
 '换型/换料后开始量产前，操作员必须先做？',
 '[{"value":"a","label":"直接开足马力赶产量"},{"value":"b","label":"通知品质做首件检验，确认合格后再批量生产"},{"value":"c","label":"把首件放一边等下班再说"},{"value":"d","label":"问下工位长能不能跳过"}]'::jsonb,
 '["b"]'::jsonb,
 '首件确认是批量生产前的质量闸门，未经首件合格确认不得批量生产。',
 '["首件","换型","质量闸门"]'::jsonb, 1),
('PT-OP-Q02', 'operator', 'PT-OP-Q02', '标准作业', 1, 'single',
 '作业指导书（WI/SOP）与习惯做法冲突时，正确做法是？',
 '[{"value":"a","label":"按习惯来，快一点"},{"value":"b","label":"按SOP执行，异常及时上报班长"},{"value":"c","label":"两种都做一点"},{"value":"d","label":"自己改SOP"}]'::jsonb,
 '["b"]'::jsonb,
 'SOP 是受控文件，操作员必须按标准执行，偏差需反馈改善而非自行变更。',
 '["SOP","标准作业","异常上报"]'::jsonb, 1),
('PT-OP-Q03', 'operator', 'PT-OP-Q03', '质量异常处置', 2, 'single',
 '生产中发现批量不良倾向时，第一时间应？',
 '[{"value":"a","label":"继续做，坏的不多就算了"},{"value":"b","label":"立即停机止住不合格输出，上报班长/品质隔离可疑品"},{"value":"c","label":"自己返工所有可疑品"},{"value":"d","label":"等巡检发现再说"}]'::jsonb,
 '["b"]'::jsonb,
 '异常处置三原则：停机、隔离、上报。先遏制输出，再分析原因。',
 '["停线","隔离","上报"]'::jsonb, 2),
('PT-OP-Q04', 'operator', 'PT-OP-Q04', '5S', 1, 'single',
 '“整理”与“整顿”的核心区别是？',
 '[{"value":"a","label":"没区别"},{"value":"b","label":"整理=区分要与不要并清除不要物；整顿=将留下物品定置定位标识"},{"value":"c","label":"整理=打扫卫生"},{"value":"d","label":"整顿=扔掉所有工具"}]'::jsonb,
 '["b"]'::jsonb,
 '整理去杂、整顿定置，两者配合才能消除寻找时间与误用风险。',
 '["5S","整理","整顿"]'::jsonb, 1),
('PT-OP-Q05', 'operator', 'PT-OP-Q05', '物料核对', 1, 'single',
 '领料/上料前，操作员应核对物料的哪些信息？',
 '[{"value":"a","label":"只看数量"},{"value":"b","label":"只照单领"},{"value":"c","label":"料号、规格、批次/有效期、数量与领料单一致"},{"value":"d","label":"外观好看就行"}]'::jsonb,
 '["c"]'::jsonb,
 '物料核对防错料，尤其是规格、批次与有效期。',
 '["防错料","批次","有效期"]'::jsonb, 1),
('PT-OP-Q06', 'operator', 'PT-OP-Q06', '生产记录', 2, 'single',
 '完工数量、报废数量填写原则是？',
 '[{"value":"a","label":"按班长说的填"},{"value":"b","label":"真实、及时、可追溯，与实物清点一致"},{"value":"c","label":"下班前凭记忆一次填完"},{"value":"d","label":"只填数量不填异常"}]'::jsonb,
 '["b"]'::jsonb,
 '生产数据是计划与追溯的基座，必须真实及时，异常同样要记录。',
 '["报工","追溯","数据真实"]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-IPQC-Q01', 'ipqc', 'PT-IPQC-Q01', '首件确认', 2, 'single',
 'IPQC 对首件的判定权限是？',
 '[{"value":"a","label":"只记录不判定"},{"value":"b","label":"按检验标准独立判定首件合格/不合格，不合格时阻止批量生产"},{"value":"c","label":"听生产主管的"},{"value":"d","label":"直接修改工艺参数"}]'::jsonb,
 '["b"]'::jsonb,
 'IPQC 首件判定是独立质量闸门，不合格即不放行批量。',
 '["首件","放行","独立判定"]'::jsonb, 2),
('PT-IPQC-Q02', 'ipqc', 'PT-IPQC-Q02', '巡检', 2, 'single',
 '巡检发现特性值靠近规格限但未超限，正确做法是？',
 '[{"value":"a","label":"不管"},{"value":"b","label":"记录数据，加密频次观察趋势并反馈，防止漂移超限"},{"value":"c","label":"立刻停线"},{"value":"d","label":"改成宽松标准"}]'::jsonb,
 '["b"]'::jsonb,
 '近限即预警，SPC 思维：趋势比单点更早暴露过程漂移。',
 '["SPC","趋势","预警"]'::jsonb, 2),
('PT-IPQC-Q03', 'ipqc', 'PT-IPQC-Q03', '不合格品处理', 3, 'single',
 '发现不合格批时，IPQC 处置顺序正确的是？',
 '[{"value":"a","label":"直接报废全部"},{"value":"b","label":"继续生产凑数"},{"value":"c","label":"隔离不合格品、标识状态、上报 MRB 评审，同时评估已流出批次"},{"value":"d","label":"只记录在案"}]'::jsonb,
 '["c"]'::jsonb,
 '隔离-标识-评审-追溯流出，这是不合格品控制的标准闭环。',
 '["MRB","隔离","追溯"]'::jsonb, 3),
('PT-IPQC-Q04', 'ipqc', 'PT-IPQC-Q04', '测量工具', 1, 'single',
 '使用量具前应确认？',
 '[{"value":"a","label":"量具在校验有效期内且状态正常"},{"value":"b","label":"量具看起来新"},{"value":"c","label":"随便借一把"},{"value":"d","label":"用一把坏的量具问题不大"}]'::jsonb,
 '["a"]'::jsonb,
 '量具受控是测量数据可信的前提，超过有效期须停用。',
 '["校验","量具受控"]'::jsonb, 1),
('PT-IPQC-Q05', 'ipqc', 'PT-IPQC-Q05', '标准执行', 2, 'single',
 '检验标准（CIP/图纸）与现场实际有出入时？',
 '[{"value":"a","label":"按现场实际来"},{"value":"b","label":"按受控标准判定，并反馈标准版本/内容问题走变更流程"},{"value":"c","label":"不检验了"},{"value":"d","label":"自己改标准"}]'::jsonb,
 '["b"]'::jsonb,
 '检验依据必须受控，标准问题通过变更流程解决而非现场妥协。',
 '["CIP","受控标准","变更"]'::jsonb, 2),
('PT-IPQC-Q06', 'ipqc', 'PT-IPQC-Q06', '问题反馈', 2, 'single',
 '连续出现同类质量问题，IPQC 应？',
 '[{"value":"a","label":"自己想办法"},{"value":"b","label":"记录并推动根源分析（人机料法环测）闭环，跟踪改善有效性"},{"value":"c","label":"提高判定放宽"},{"value":"d","label":"上报一次就不管"}]'::jsonb,
 '["b"]'::jsonb,
 '系统性质量问题要追根因并验证改善效果，形成 PDCA 闭环。',
 '["根因分析","PDCA","改善有效性"]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-EQ-Q01', 'equipment_engineer', 'PT-EQ-Q01', '点检保养', 2, 'single',
 '设备点检发现轻微异常，但还能运行，正确做法是？',
 '[{"value":"a","label":"等坏了再修"},{"value":"b","label":"记录异常并评估隐患等级，安排预防性处置，防止劣化扩大"},{"value":"c","label":"忽略"},{"value":"d","label":"上报就行不处理"}]'::jsonb,
 '["b"]'::jsonb,
 'TPM 理念：在劣化发生前处置，点检记录是预测性维护输入。',
 '["TPM","预防性维护","劣化"]'::jsonb, 2),
('PT-EQ-Q02', 'equipment_engineer', 'PT-EQ-Q02', '故障定位', 3, 'single',
 '设备突发停机，正确的排查顺序是？',
 '[{"value":"a","label":"直接拆大部件"},{"value":"b","label":"先确认能源/气/电到位→报警信息→按线路与逻辑逐级排查，先简单后复杂"},{"value":"c","label":"换整套备件"},{"value":"d","label":"让操作员反复试"}]'::jsonb,
 '["b"]'::jsonb,
 '系统化排障：从源头与现象入手，用报警与逻辑图缩小范围。',
 '["故障树","报警","逐级排查"]'::jsonb, 3),
('PT-EQ-Q03', 'equipment_engineer', 'PT-EQ-Q03', '维修记录', 2, 'single',
 '维修完成后必须记录？',
 '[{"value":"a","label":"不用记录"},{"value":"b","label":"故障现象、根因、更换件/修法、工时与停机时长，形成履历"},{"value":"c","label":"只记换了什么"},{"value":"d","label":"只报修一下"}]'::jsonb,
 '["b"]'::jsonb,
 '维修履历是 MTTR/MTBF 分析与备件策略的数据基础。',
 '["MTBF","MTTR","履历"]'::jsonb, 2),
('PT-EQ-Q04', 'equipment_engineer', 'PT-EQ-Q04', '备件管理', 2, 'single',
 '常用易损备件缺货时，正确的预防动作是？',
 '[{"value":"a","label":"等坏了再说"},{"value":"b","label":"根据更换频率设定安全库存并补充，避免停机等件"},{"value":"c","label":"买一大堆全放着"},{"value":"d","label":"不换备件"}]'::jsonb,
 '["b"]'::jsonb,
 '备件策略按消耗频率与关键性设定库存水位。',
 '["安全库存","备件策略"]'::jsonb, 2),
('PT-EQ-Q05', 'equipment_engineer', 'PT-EQ-Q05', '安全作业', 1, 'single',
 '设备维护前必须执行的作业安全措施？',
 '[{"value":"a","label":"直接上手"},{"value":"b","label":"断电/断气、挂牌上锁（LOTO）、确认能量释放后再作业"},{"value":"c","label":"只断电不断气"},{"value":"d","label":"挂牌就行不断电"}]'::jsonb,
 '["b"]'::jsonb,
 'LOTO 是防误启动与能量伤害的核心安全措施。',
 '["LOTO","能量隔离","挂牌上锁"]'::jsonb, 1),
('PT-EQ-Q06', 'equipment_engineer', 'PT-EQ-Q06', '异常升级', 2, 'single',
 '故障复杂无法短时修复且影响生产时，应？',
 '[{"value":"a","label":"自己慢慢修"},{"value":"b","label":"评估修复ETA与停产影响，升级上报并同步生产计划调整"},{"value":"c","label":"隐瞒停机"},{"value":"d","label":"让生产先硬撑"}]'::jsonb,
 '["b"]'::jsonb,
 '停机信息透明并及时同步计划，才能把损失降到最低。',
 '["升级","停机通报"]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-PS-Q01', 'production_supervisor', 'PT-PS-Q01', '班前会', 1, 'single',
 '班前会（站会）应包含的核心要素？',
 '[{"value":"a","label":"只看产量"},{"value":"b","label":"昨日达成与异常回顾、今日目标与安全提示、人员/物料/设备准备状态确认"},{"value":"c","label":"只传达领导指示"},{"value":"d","label":"有时间才开"}]'::jsonb,
 '["b"]'::jsonb,
 '班前会统一目标、暴露瓶颈、对齐准备状态，是现场管理第一环。',
 '["班前会","现场管理"]'::jsonb, 1),
('PT-PS-Q02', 'production_supervisor', 'PT-PS-Q02', '瓶颈管理', 2, 'single',
 '产线因瓶颈工位欠产，主管应优先？',
 '[{"value":"a","label":"全线加班一起干"},{"value":"b","label":"明确瓶颈所在，优先保证瓶颈连续生产，并解决其待料/待机"},{"value":"c","label":"只催瓶颈员工"},{"value":"d","label":"给所有工位平均加人"}]'::jsonb,
 '["b"]'::jsonb,
 '瓶颈决定产线产出（TOC），一切资源优先保瓶颈。',
 '["TOC","瓶颈","产出"]'::jsonb, 2),
('PT-PS-Q03', 'production_supervisor', 'PT-PS-Q03', '跨部门协调', 2, 'single',
 '物料短缺导致待料停机，主管应？',
 '[{"value":"a","label":"让工人等"},{"value":"b","label":"先盘可用量/替代料并同步PMC，按优先级重新安排在线顺序，减少整线停摆"},{"value":"c","label":"自己去车间外面找料"},{"value":"d","label":"直接扣别的订单的料"}]'::jsonb,
 '["b"]'::jsonb,
 '待料时优先保重点订单与瓶颈，而非全停，并与PMC协同。',
 '["待料","PMC协同","优先级"]'::jsonb, 2),
('PT-PS-Q04', 'production_supervisor', 'PT-PS-Q04', '人员调配', 2, 'single',
 '某工位人员请假导致缺员，主管合理做法是？',
 '[{"value":"a","label":"少人就慢点"},{"value":"b","label":"评估多能工顶岗/工序重排，避免质量与安全风险，缺口无法覆盖则提前上报计划"},{"value":"c","label":"随便拉个人顶"},{"value":"d","label":"让班长顶一天"}]'::jsonb,
 '["b"]'::jsonb,
 '人员调配以多能工与安全质量为前提，缺口要提前暴露给计划。',
 '["多能工","人员调配"]'::jsonb, 2),
('PT-PS-Q05', 'production_supervisor', 'PT-PS-Q05', '现场改善', 2, 'single',
 '员工提出一条合理改善建议，主管应？',
 '[{"value":"a","label":"先放着"},{"value":"b","label":"评估可行性，试点验证后固化到SOP并激励员工"},{"value":"c","label":"直接全面推广"},{"value":"d","label":"让员工自己去改"}]'::jsonb,
 '["b"]'::jsonb,
 '改善按“验证-固化-激励”推进，防止未验证直接铺开。',
 '["改善提案","试点","标准化"]'::jsonb, 2),
('PT-PS-Q06', 'production_supervisor', 'PT-PS-Q06', '数据日报', 1, 'single',
 '班次结束时主管日报应确保？',
 '[{"value":"a","label":"只写产量"},{"value":"b","label":"产量/达成率、质量不良、异常与处置、待办事项真实完整"},{"value":"c","label":"报喜不报忧"},{"value":"d","label":"拖到第二天"}]'::jsonb,
 '["b"]'::jsonb,
 '真实完整的日报是管理层决策与计划修正的依据。',
 '["日报","数据完整"]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-WK-Q01', 'warehouse_keeper', 'PT-WK-Q01', '收货核对', 1, 'single',
 '供应商来货入库前，仓管必须核对？',
 '[{"value":"a","label":"只看箱数"},{"value":"b","label":"送货单与采购订单一致性：料号、规格、数量、批次、随货单据"},{"value":"c","label":"直接签字"},{"value":"d","label":"先放一边"}]'::jsonb,
 '["b"]'::jsonb,
 '收货是三单一致的第一道闸门，防止错收与超收。',
 '["三单一致","收货","批次"]'::jsonb, 1),
('PT-WK-Q02', 'warehouse_keeper', 'PT-WK-Q02', '先进先出', 2, 'single',
 '保证先进先出（FIFO）的正确做法是？',
 '[{"value":"a","label":"按摆放顺手拿"},{"value":"b","label":"按批次日期管理，先入库批次先发放，并防止混批"},{"value":"c","label":"新的放前面方便"},{"value":"d","label":"随意"}]'::jsonb,
 '["b"]'::jsonb,
 'FIFO 靠批次管理实现，防止呆滞与保质期过期。',
 '["FIFO","批次管理"]'::jsonb, 2),
('PT-WK-Q03', 'warehouse_keeper', 'PT-WK-Q03', '账实一致', 2, 'single',
 '发现账卡物不一致时，仓管应？',
 '[{"value":"a","label":"随便改账"},{"value":"b","label":"暂停发料并盘查差异，查清原因后按流程调整账务"},{"value":"c","label":"装没看见"},{"value":"d","label":"按多的一方记"}]'::jsonb,
 '["b"]'::jsonb,
 '账实差异要追因处理，杜绝无依据改账。',
 '["盘点","账实一致"]'::jsonb, 2),
('PT-WK-Q04', 'warehouse_keeper', 'PT-WK-Q04', '呆滞料', 3, 'single',
 '长期不动的呆滞物料，仓管应？',
 '[{"value":"a","label":"一直放着"},{"value":"b","label":"标识并定期反馈，推动评审利用/替代/处置，释放库存资金"},{"value":"c","label":"直接报废"},{"value":"d","label":"堆到墙角"}]'::jsonb,
 '["b"]'::jsonb,
 '呆滞料要主动暴露并推动处置，而非放任占用资金。',
 '["呆滞料","库存周转"]'::jsonb, 3),
('PT-WK-Q05', 'warehouse_keeper', 'PT-WK-Q05', '先进先出-质量', 2, 'single',
 '某批次被通知有质量异常，仓管应？',
 '[{"value":"a","label":"继续发"},{"value":"b","label":"立即冻结该批次库存，停止发放，配合品质隔离并评估已流出部分"},{"value":"c","label":"自己判断没问题就发"},{"value":"d","label":"只口头提醒"}]'::jsonb,
 '["b"]'::jsonb,
 '异常批次须冻结追溯，防止流入生产。',
 '["冻结","追溯","批次"]'::jsonb, 2),
('PT-WK-Q06', 'warehouse_keeper', 'PT-WK-Q06', '库存安全', 1, 'single',
 '仓库安全管理的正确做法？',
 '[{"value":"a","label":"通道堆满料"},{"value":"b","label":"通道畅通、重不压轻、危险品分区隔离、消防器材不被遮挡"},{"value":"c","label":"货架随便堆高"},{"value":"d","label":"下班不锁门方便"}]'::jsonb,
 '["b"]'::jsonb,
 '仓库安全：通道、堆码、危险品与消防是核心红线。',
 '["仓库安全","危险品","消防"]'::jsonb, 1)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();
