-- 095: PMC计划员训练题库大幅增强（6大模块：MRP实操/生产计划/产能规划/短缺控制/库存E&O/OTD出货）

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-PMC-Q11', 'pmc', 'PT-PMC-Q11', 'MRP参数校验', 3, 'multiple',
 '跑 MRP 之前，必须校验哪些物料参数，否则结果全是垃圾？（多选）',
 '[{"value":"a","label":"Lead Time（采购周期）"},{"value":"b","label":"MOQ（最小起订量）"},{"value":"c","label":"Safety Stock（安全库存）"},{"value":"d","label":"Scrap Rate（损耗率）"}]'::jsonb,
 '["a","b","c","d"]'::jsonb,
 '四大参数直接决定净需求是否准确：Lead Time 决定下单时点，MOQ 决定批量，安全库存保缓冲，损耗率补生产损耗；参数不准，跑出来的单全部失真。',
 '["MRP","Lead Time","MOQ","Safety Stock","Scrap Rate"]'::jsonb, 3),
('PT-PMC-Q12', 'pmc', 'PT-PMC-Q12', 'MRP净需求', 3, 'single',
 '系统净需求公式为：净需求 = 毛需求 - 可用库存 + 安全库存。其中可用库存应包含哪些？',
 '[{"value":"a","label":"只要现有库存"},{"value":"b","label":"现有库存 + 在途采购 + 在制工单"},{"value":"c","label":"现有库存 + 销售订单扣减"},{"value":"d","label":"在途采购 - 在制工单"}]'::jsonb,
 '["b"]'::jsonb,
 '可用库存 = 现有库存 + 在途采购 + 在制工单。实操重点：在途数据需核对是否过期，僵尸单（系统未关闭）要手动清理，否则净需求虚高或虚低。',
 '["MRP","净需求","在途","僵尸单"]'::jsonb, 3),
('PT-PMC-Q13', 'pmc', 'PT-PMC-Q13', 'MRP例外处理', 3, 'single',
 'MRP 跑完后，不能直接下单据，正确的处理顺序是？',
 '[{"value":"a","label":"全部自动转为采购申请与工单"},{"value":"b","label":"先看例外信息（提前期不足/批量调整），按交期紧迫度排序，微调数量凑整包装和日期避开车历，再转正式单据"},{"value":"c","label":"直接发给采购不用审核"},{"value":"d","label":"跳过 MRP 全部手工下单"}]'::jsonb,
 '["b"]'::jsonb,
 'MRP 输出的是计划订单草稿。关键动作：先处理例外信息，按交期紧迫度排序，手动微调数量（凑整包装数）和日期（考虑周末/海关/出货），确认后再转化为正式 PR/MO。',
 '["MRP","例外信息","计划订单","转单"]'::jsonb, 3),
('PT-PMC-Q14', 'pmc', 'PT-PMC-Q14', 'MPS排程', 3, 'single',
 'MPS（主生产计划）冻结区与浮动区的正确管理方式是？',
 '[{"value":"a","label":"冻结区内可随意插单，方便销售"},{"value":"b","label":"未来1-3周为冻结区不可随意插单；未来4-8周为浮动区可调整"},{"value":"c","label":"所有订单随时可插单"},{"value":"d","label":"只有月底才冻结"}]'::jsonb,
 '["b"]'::jsonb,
 'MPS 滚动计划：近 1-3 周锁定（冻结区）保产能稳定，4-8 周浮动区可调。冻结区内插单必须走异常仲裁，杜绝频繁打乱产线。',
 '["MPS","冻结区","浮动区","滚动计划"]'::jsonb, 3),
('PT-PMC-Q15', 'pmc', 'PT-PMC-Q15', '序列优化', 2, 'single',
 '生产排程做序列调整时，优先考虑什么以减少停机损失？',
 '[{"value":"a","label":"按订单金额从大到小排"},{"value":"b","label":"优先将同型号/同颜色订单连续排在一起，减少换模时间（Changeover）"},{"value":"c","label":"按客户重要性排"},{"value":"d","label":"随意排序尽快开线"}]'::jsonb,
 '["b"]'::jsonb,
 '同型号/同颜色连续排可减少换模与清洗停机。输出《周/日生产排程表》，换模成本是序列决策的核心变量。',
 '["排程","Changeover","序列优化"]'::jsonb, 2),
('PT-PMC-Q16', 'pmc', 'PT-PMC-Q16', '产能规划', 3, 'multiple',
 '产能负荷超载（>120%）时，可采取的动作有哪些？（多选）',
 '[{"value":"a","label":"内部加班/调休"},{"value":"b","label":"外协（发外包）"},{"value":"c","label":"与销售协商将部分订单延期（Push Out）"},{"value":"d","label":"直接取消客户订单"}]'::jsonb,
 '["a","b","c"]'::jsonb,
 '超载处置顺序：先内部挖潜（加班/调休），再外协，最后与销售协商 Push Out 延期。取消订单不是方案。必须维护《瓶颈工序负载监控表》（红黄绿灯看板）。',
 '["RCCP","产能负荷","外协","Push Out","红黄绿灯"]'::jsonb, 3),
('PT-PMC-Q17', 'pmc', 'PT-PMC-Q17', 'RCCP与CRP', 3, 'single',
 'RCCP（粗能力计划）与 CRP（细能力需求计划）的正确区分是？',
 '[{"value":"a","label":"RCCP 针对已释放工单，CRP 针对主计划"},{"value":"b","label":"RCCP 针对瓶颈工序粗算总负荷；CRP 针对已释放工单按天/班次核可用工时"},{"value":"c","label":"两者完全相同"},{"value":"d","label":"RCCP 只查设备，CRP 只查人员"}]'::jsonb,
 '["b"]'::jsonb,
 'RCCP：对主计划核算瓶颈工序总负荷（需求工时 = 计划产量 x 标准工时 CT）。CRP：对已释放工单细化到每天每班次可用工时（扣除保养、开会、吃饭）。层层细化互为验证。',
 '["RCCP","CRP","瓶颈工序","CT"]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-PMC-Q18', 'pmc', 'PT-PMC-Q18', '齐套检查', 2, 'single',
 '工单开工前 T-3 天做齐套检查时，应重点关注哪类物料？',
 '[{"value":"a","label":"所有物料平均关注"},{"value":"b","label":"长周期物料和唯一供应商（Single Source）物料"},{"value":"c","label":"只查看低价物料"},{"value":"d","label":"只查看库存最多的物料"}]'::jsonb,
 '["b"]'::jsonb,
 '长周期与单一来源物料风险最高，缺失难补。齐套检查在 T-3 全量核对，这两类须提前锁定与跟催。',
 '["齐套","Kitting","Single Source","T-3"]'::jsonb, 2),
('PT-PMC-Q19', 'pmc', 'PT-PMC-Q19', '缺料预警', 2, 'single',
 '针对短缺料，采购员给出的哪种反馈才是合格的？',
 '[{"value":"a","label":"正在催"},{"value":"b","label":"确切的承诺交期（Committed Date）"},{"value":"c","label":"大概下周"},{"value":"d","label":"应该快到了"}]'::jsonb,
 '["b"]'::jsonb,
 '缺料跟进的核心是拿到确切承诺交期（Committed Date），而非模糊的“正在催”。每日更新《短缺物料清单》，无确切交期的短缺必须升级。',
 '["短缺","Committed Date","交期承诺"]'::jsonb, 2),
('PT-PMC-Q20', 'pmc', 'PT-PMC-Q20', '欠料处置', 3, 'single',
 '出现欠料无法按期到位时，PMC 的正确动作是？',
 '[{"value":"a","label":"产线停下来等料"},{"value":"b","label":"启动 PULL IN（提前）或替代料流程；仍无法解决则调整生产计划，缺料工单后移、有料工单提前，坚决不让线上等料"},{"value":"c","label":"不通知生产自己做"},{"value":"d","label":"把欠料单静默取消"}]'::jsonb,
 '["b"]'::jsonb,
 '欠料处置三步：先追（Pull In/替代料），再调（生产计划前后置换），关键红线——不允许线上等料，保证产能不因缺料空转。',
 '["欠料","Pull In","替代料","生产计划调整"]'::jsonb, 3),
('PT-PMC-Q21', 'pmc', 'PT-PMC-Q21', '库存DOH', 2, 'single',
 'DOH（库存持有天数）的计算公式与目标标准是？',
 '[{"value":"a","label":"DOH = 现有库存金额 / 过去3个月平均日消耗成本，目标通常 30~45 天"},{"value":"b","label":"DOH = 未来交期天数"},{"value":"c","label":"DOH = 库存数量 x 货值"},{"value":"d","label":"DOH 越高越好"}]'::jsonb,
 '["a"]'::jsonb,
 'DOH = 现有库存金额 / 过去3个月平均日消耗成本。目标 30~45 天；DOH > 60 天物料标红预警，纳入 E&O 评审。',
 '["DOH","库存周转","日消耗"]'::jsonb, 2),
('PT-PMC-Q22', 'pmc', 'PT-PMC-Q22', '呆滞认定', 3, 'multiple',
 'E&O（呆滞与过剩）认定中，呆料与滞料的正确分类是？（多选）',
 '[{"value":"a","label":"呆料：无任何需求"},{"value":"b","label":"滞料：有需求但未来3个月覆盖天数 > 180天"},{"value":"c","label":"呆料：库存金额超过10万"},{"value":"d","label":"滞料：到货太慢"}]'::jsonb,
 '["a","b"]'::jsonb,
 '呆料 = 无任何需求；滞料 = 有需求但未来3个月覆盖天数 > 180 天。按月分类认定，作为月度处置会议输入。',
 '["E&O","呆料","滞料","分类"]'::jsonb, 3),
('PT-PMC-Q23', 'pmc', 'PT-PMC-Q23', '呆滞处置', 3, 'single',
 '针对已认定的 E&O 物料，月度处置的顺序正确的是？',
 '[{"value":"a","label":"直接报废"},{"value":"b","label":"替代品使用（优先）→ 退回供应商 → 低价甩卖 → 报废（需高层财务签字）"},{"value":"c","label":"继续堆在仓库"},{"value":"d","label":"打折给生产用"}]'::jsonb,
 '["b"]'::jsonb,
 '处置顺序：①替代品使用（优先）②退回供应商 ③低价甩卖给贸易商 ④报废（高层财务签字）。必须形成会议纪要；新项目导入需同步输出《E&O预估报告》从源头控死。',
 '["E&O","处置","会议纪要","E&O预估报告"]'::jsonb, 3)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();

INSERT INTO position_training_questions
    (id, position_code, question_code, skill, difficulty, question_type, prompt,
     options, answer, explanation, reference_terms, points)
VALUES
('PT-PMC-Q24', 'pmc', 'PT-PMC-Q24', 'ATP计算', 3, 'single',
 '接到新订单时，ATP（可承诺量）的可用量计算逻辑是？',
 '[{"value":"a","label":"可用量 = 现有库存 + 在产 - 已占用；若不足按先到先得分配"},{"value":"b","label":"可用量 = 现有库存 - 在产"},{"value":"c","label":"可用量 = 未来采购到货量"},{"value":"d","label":"可用量 = 客户要多少给多少"}]'::jsonb,
 '["a"]'::jsonb,
 'ATP = 现有库存 + 在产 - 已占用。库存不足时按先到先得（FCFS）分配，保证承诺不超卖。',
 '["ATP","可承诺量","先到先得"]'::jsonb, 3),
('PT-PMC-Q25', 'pmc', 'PT-PMC-Q25', '发货优先级', 3, 'single',
 '系统自动锁定库存时，发货优先级的标准顺序是？',
 '[{"value":"a","label":"紧急加急单（客户停线风险）→ 整柜/整车满载单（省运费）→ 普通交期单"},{"value":"b","label":"普通交期单优先"},{"value":"c","label":"按客户规模大小排"},{"value":"d","label":"按付款速度排"}]'::jsonb,
 '["a"]'::jsonb,
 '标准顺序：①紧急加急单（客户停线风险）②整柜/整车满载单（节省运费）③普通交期单。严禁因“发货方便”挪用紧急单库存。',
 '["发货优先级","加急","满载","库存锁定"]'::jsonb, 3),
('PT-PMC-Q26', 'pmc', 'PT-PMC-Q26', 'CTP交期承诺', 3, 'single',
 '库存不足时回复客户最新交期（CTP），应计算哪几段时间之和？',
 '[{"value":"a","label":"生产剩余天数 + 物流运输天数（海运/空运）+ 报关清关天数"},{"value":"b","label":"只算生产天数"},{"value":"c","label":"只算运输天数"},{"value":"d","label":"按销售说的日期"}]'::jsonb,
 '["a"]'::jsonb,
 'CTP = 生产剩余天数 + 物流运输天数（海运/空运）+ 报关清关天数。三段合计才是可信交付承诺。',
 '["CTP","交期承诺","物流","清关"]'::jsonb, 3),
('PT-PMC-Q27', 'pmc', 'PT-PMC-Q27', '出货前置', 2, 'single',
 '出货前 T-1 天与 T 日系统操作的正确做法是？',
 '[{"value":"a","label":"T日才临时拣货"},{"value":"b","label":"T-1 完成拣货、贴标、二次称重；T日系统过账（Post Good Issue）并上传 Packing List & Invoice 至客户门户"},{"value":"c","label":"T日装车后再过账"},{"value":"d","label":"不贴标直接发"}]'::jsonb,
 '["b"]'::jsonb,
 '出货前置动作：T-1 拣货、贴标、二次称重；T 日系统 Post Good Issue 过账，同步上传 Packing List & Invoice 到客户门户，确保准数、准址、可追溯。',
 '["OTD","Post Good Issue","Packing List","T-1"]'::jsonb, 2),
('PT-PMC-Q28', 'pmc', 'PT-PMC-Q28', 'S&OP协同', 2, 'single',
 '每周产销协同（S&OP）会议的核心输入应该是？',
 '[{"value":"a","label":"只讨论产能"},{"value":"b","label":"生产、采购、销售三方共同对计划与产能对齐：调计划、调产能、定优先级"},{"value":"c","label":"只由老板拍板"},{"value":"d","label":"销售单方面改交期"}]'::jsonb,
 '["b"]'::jsonb,
 'S&OP 是生产、采购、销售三方协同：调计划、调产能、定优先级。产出是各方都认账的产销平衡计划。',
 '["S&OP","产销协同","计划对齐"]'::jsonb, 2),
('PT-PMC-Q29', 'pmc', 'PT-PMC-Q29', '日常优先级', 1, 'single',
 'PMC 每日工作的最高优先级（救火级）是哪两项？',
 '[{"value":"a","label":"缺料控制（今天没料产线停）+ 出货 OTD（今天发不出货）"},{"value":"b","label":"库存周转天数"},{"value":"c","label":"MRP 参数设置"},{"value":"d","label":"E&O 财务计提"}]'::jsonb,
 '["a"]'::jsonb,
 '保交付优先：今天没料、今天发不出货，老板会立刻找你。库存偏高、产能粗排偏差，短期不可见。先把救火级做扎实。',
 '["优先级","缺料","OTD"]'::jsonb, 1),
('PT-PMC-Q30', 'pmc', 'PT-PMC-Q30', '交期红线', 2, 'single',
 '工单释放前“物料红线”的含义是？',
 '[{"value":"a","label":"所有物料必须全部到齐才开工"},{"value":"b","label":"每颗料到位时间不得晚于其上线时间，超红线即阻塞"},{"value":"c","label":"物料到了红线日期就作废"},{"value":"d","label":"红线是给采购看的口头说法"}]'::jsonb,
 '["b"]'::jsonb,
 '物料红线 = 每颗料的上线极限时间。ETA 晚于红线则该料阻塞工单，需提前升级或调整排产，不能等开工才发现缺料。',
 '["物料红线","上线时间","阻塞"]'::jsonb, 2)
ON CONFLICT (id) DO UPDATE SET
    position_code = EXCLUDED.position_code, skill = EXCLUDED.skill,
    difficulty = EXCLUDED.difficulty, question_type = EXCLUDED.question_type,
    prompt = EXCLUDED.prompt, options = EXCLUDED.options, answer = EXCLUDED.answer,
    explanation = EXCLUDED.explanation, reference_terms = EXCLUDED.reference_terms,
    points = EXCLUDED.points, is_active = TRUE, updated_at = NOW();
